# .travis.yaml for gipert/bayesian-blocks
#
# Author: Luigi Pertoldi - luigi.pertoldi@hotmail.it
# Created: Tue 15 Jan 2019
#

notifications:
  - email: false

branches:
  only:
    - master

matrix:
  include:

    - os: linux
      language: cpp
      compiler: gcc
      sudo: required
      services: docker
      env: DOCKER_IMAGE=gipert/root-cern:6.16.00
      before_install:
        - docker pull "$DOCKER_IMAGE"
        - export DOCKER_INSTANCE=`docker run -it -d "$DOCKER_IMAGE" /bin/bash`
        - docker cp . "$DOCKER_INSTANCE:/root/bayesian-blocks"
      script:
        - docker exec "$DOCKER_INSTANCE" /bin/sh -c \
            "cd /root/bayesian-blocks/cpp/test && LD_LIBRARY_PATH=\$PWD make test"

    - os: osx
      osx_image: xcode11
      language: cpp
      compiler: clang
      addons:
        homebrew:
      script:
        - brew install --force-bottle root
        - cd cpp/test && make test

    - os: linux
      language: julia
      julia: 1.0
      before_install: julia -e 'using Pkg; Pkg.add("StatsBase"); Pkg.add("ProgressMeter")'
      script: cd julia/test/ && ./run_tests.sh

# vim: tabstop=2 shiftwidth=2 expandtab
